"""Import all models so that ``Base.metadata`` is complete (Alembic autogenerate)."""

from app.models.assistant import Assistant, AssistantVersion
from app.models.audit_log import AuditLog
from app.models.base import Base
from app.models.conversation import Conversation, Message
from app.models.document_gen import (
    DOCGEN_STATUS_APPROVED,
    DOCGEN_STATUS_DRAFT,
    DOCGEN_STATUS_REJECTED,
    DOCGEN_STATUS_SUBMITTED,
    DocumentTemplate,
    GeneratedDocument,
)
from app.models.integration import ApiKey
from app.models.knowledge import (
    DOC_STATUS_ARCHIVED,
    DOC_STATUS_DRAFT,
    DOC_STATUS_FAILED,
    DOC_STATUS_INDEXED,
    DOC_STATUS_PROCESSING,
    JOB_STATUS_FAILED,
    JOB_STATUS_PENDING,
    JOB_STATUS_RUNNING,
    JOB_STATUS_SUCCEEDED,
    KB_GROUP_PERM_APPROVE,
    KB_GROUP_PERM_READ,
    KB_GROUP_PERM_WRITE,
    Document,
    DocumentChunk,
    DocumentVersion,
    KnowledgeBase,
    KnowledgeBaseGroupPermission,
    ProcessingJob,
)
from app.models.meeting import (
    MEETING_STATUS_COMPLETED,
    MEETING_STATUS_FAILED,
    RECORDING_STATUS_COMPLETED,
    RECORDING_STATUS_FAILED,
    RECORDING_STATUS_PENDING,
    RECORDING_STATUS_TRANSCRIBING,
    Meeting,
    MeetingRecording,
    MeetingSummary,
    MeetingTranscript,
)
from app.models.organization import Organization
from app.models.rbac import (
    SCOPE_GLOBAL,
    SCOPE_ORG,
    Group,
    Permission,
    Role,
    RolePermission,
    UserGroup,
    UserRole,
)
from app.models.refresh_token import RefreshToken
from app.models.user import User
from app.models.workflow import (
    APPROVAL_APPROVED,
    APPROVAL_PENDING,
    APPROVAL_REJECTED,
    WF_RUN_COMPLETED,
    WF_RUN_FAILED,
    WF_RUN_PENDING,
    WF_RUN_RUNNING,
    WF_RUN_WAITING_APPROVAL,
    WF_STATUS_ACTIVE,
    WF_STATUS_ARCHIVED,
    WF_STATUS_DRAFT,
    ApprovalStep,
    WorkflowDefinition,
    WorkflowRun,
)

__all__ = [
    "ApiKey",
    "ApprovalStep",
    "APPROVAL_APPROVED",
    "APPROVAL_PENDING",
    "APPROVAL_REJECTED",
    "Assistant",
    "AssistantVersion",
    "AuditLog",
    "Base",
    "Conversation",
    "DOC_STATUS_ARCHIVED",
    "DOC_STATUS_DRAFT",
    "DOC_STATUS_FAILED",
    "DOC_STATUS_INDEXED",
    "DOC_STATUS_PROCESSING",
    "Document",
    "DocumentChunk",
    "DocumentVersion",
    "DocumentTemplate",
    "GeneratedDocument",
    "DOCGEN_STATUS_APPROVED",
    "DOCGEN_STATUS_DRAFT",
    "DOCGEN_STATUS_REJECTED",
    "DOCGEN_STATUS_SUBMITTED",
    "Group",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_PENDING",
    "JOB_STATUS_RUNNING",
    "JOB_STATUS_SUCCEEDED",
    "KB_GROUP_PERM_APPROVE",
    "KB_GROUP_PERM_READ",
    "KB_GROUP_PERM_WRITE",
    "KnowledgeBase",
    "KnowledgeBaseGroupPermission",
    "MEETING_STATUS_COMPLETED",
    "MEETING_STATUS_FAILED",
    "Meeting",
    "MeetingRecording",
    "MeetingSummary",
    "MeetingTranscript",
    "Message",
    "Organization",
    "Permission",
    "ProcessingJob",
    "RECORDING_STATUS_COMPLETED",
    "RECORDING_STATUS_FAILED",
    "RECORDING_STATUS_PENDING",
    "RECORDING_STATUS_TRANSCRIBING",
    "RefreshToken",
    "Role",
    "RolePermission",
    "SCOPE_GLOBAL",
    "SCOPE_ORG",
    "User",
    "UserGroup",
    "UserRole",
    "WF_RUN_COMPLETED",
    "WF_RUN_FAILED",
    "WF_RUN_PENDING",
    "WF_RUN_RUNNING",
    "WF_RUN_WAITING_APPROVAL",
    "WF_STATUS_ACTIVE",
    "WF_STATUS_ARCHIVED",
    "WF_STATUS_DRAFT",
    "WorkflowDefinition",
    "WorkflowRun",
]
